<?php

return [
  'GBP' => 'Pound sterling', 
  'EUR' => 'European euro',
  'USD' => 'United States dollar',
  'RUB' => 'Russian ruble',
  'CAD' => 'Canadian dollar',
  'HKD' => 'Hong Kong dollar',
  'ISK' => 'Icelandic krona',
  'PHP' => 'Philippine peso',
  'DKK' => 'Danish krone',
  'HUF' => 'Hungarian forint',
  'CZK' => 'Czech koruna',
  'RON' => 'Romanian leu',
  'SEK' => 'Swedish krona',
  'IDR' => 'Indonesian rupiah',
  'INR' => 'Indian rupee',
  'BRL' => 'Brazilian real',
  'HRK' => 'Croatian kuna',
  'JPY' => 'Japanese yen',
  'THB' => 'Thai baht',
  'CHF' => 'Swiss franc',
  'MYR' => 'Malaysian ringgit',
  'BGN' => 'Bulgarian lev',
  'TRY' => 'Turkish lira',
  'CNY' => 'Chinese Yuan Renminbi',
  'NOK' => 'Norwegian krone',
  'NZD' => 'New Zealand dollar',
  'ZAR' => 'South African rand',
  'MXN' => 'Mexican peso',
  'SGD' => 'Singapore dollar',
  'AUD' => 'Australian dollar',
  'ILS' => 'Israeli new shekel',
  'KRW' => 'South Korean won',
  'PLN' => 'Polish zloty'
];
